// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7RvF_3drG-9euYoOrzLGifMp49sAfT34',
    appId: '1:577777388342:web:f51eaec70329394ef08197',
    messagingSenderId: '577777388342',
    projectId: 'wima-wallet',
    authDomain: 'wima-wallet.firebaseapp.com',
    storageBucket: 'wima-wallet.appspot.com',
    measurementId: 'G-VGFSLKG27N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdOrCBxLNXgYb55lJiJf1GQLji2y7SWQQ',
    appId: '1:577777388342:android:0e27b9433132ec8ef08197',
    messagingSenderId: '577777388342',
    projectId: 'wima-wallet',
    storageBucket: 'wima-wallet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG6pgzoR6348YbboUjIHPqW2tSLCzLDS0',
    appId: '1:577777388342:ios:679a9db494c6020ff08197',
    messagingSenderId: '577777388342',
    projectId: 'wima-wallet',
    storageBucket: 'wima-wallet.appspot.com',
    iosBundleId: 'com.example.wimaWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG6pgzoR6348YbboUjIHPqW2tSLCzLDS0',
    appId: '1:577777388342:ios:c2b8a984d7d51b2ff08197',
    messagingSenderId: '577777388342',
    projectId: 'wima-wallet',
    storageBucket: 'wima-wallet.appspot.com',
    iosBundleId: 'com.example.wimaWallet.RunnerTests',
  );
}
